### ISSUE TITLE
Why isn't this updated?

### ISSUE THREAD

**Issue by calvinbaart** [grate-driver/mesa#1]
Might be a bit rude to ask (probably some good reason for) but why isn't the Gallium3D driver updated for Tegra?

**Comment by Gnurou** [comment]
This driver is for older Tegra chips (Tegra 2 to 4), which is probably why it is not getting much love. Tegra K1 and Tegra X1 are supported (or in the process of being supported) in Mesa.

**Comment by kusma** [comment]
Well, what happened was that @thierryreding (who was the driving force on the the gallium-driver effort) got hired by NVIDIA, which resulted in him not being legally allowed (nor have the time) to work on this.

I've been playing around a bit more with the reverse-engineering, but not on the mesa-driver.

**Comment by digetx** [comment]
NVIDIA keep secret the 3d part of GPU. So we need to understand how HW works first to be able to do anything useful on mesa side, thats turned out to be not that easy and quite time consumptive. However still moving.
