### ISSUE TITLE
mesa-21.1.0 fails to build with llvm support 

### ISSUE THREAD

**Issue by hedmo** [grate-driver/mesa#14]
mesa-21.1.0 fails to build with llvm support because of this commit:
https://github.com/grate-driver/mesa/commit/06be898392a149afbbb6c2ad1ef596ee56019d6f .

the error is : 

/mesa-76cfc1c0905dfd2177d7aaa117989cc862d4b851/src/gallium/drivers/llvmpipe/lp_screen.c: In function ‘llvmpipe_create_screen’:
../mesa-76cfc1c0905dfd2177d7aaa117989cc862d4b851/src/gallium/drivers/llvmpipe/lp_screen.c:891:9: error: ‘util_cpu_caps’ undeclared (first use in this function); did you mean ‘util_cpu_caps_t’?
  891 |    if (!util_cpu_caps.has_neon)
      |         ^~~~~~~~~~~~~
      |         util_cpu_caps_t
../mesa-76cfc1c0905dfd2177d7aaa117989cc862d4b851/src/gallium/drivers/llvmpipe/lp_screen.c:891:9: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.

**Comment by digetx** [comment]
Thank you, I haven't build-tested llvm. Should be fixed now.

**Comment by hedmo** [comment]
will check at ones...

**Comment by hedmo** [comment]
@digetx : it worked . thank you for the fast fix . and now you got a PR : https://github.com/grate-driver/grate-overlay/pull/11 :)
