### ISSUE TITLE
building hints needed

### ISSUE THREAD

**Issue by a-andreyev** [grate-driver/mesa#6]
Hello!
I've brushed off the dust from my toshiba ac100 with tegra 2.

I'm using archlinux arm armv7h and sucessfully built `xf86-video-opentegra`, `libvdpau-tegra` and `libdrm` from your awesome grate project on the device directly (wrapped build commands from [here](https://gist.github.com/digetx/99d62b96823bdfe2dc49dfbd372a65e6) to PKGBUILDs).

So now I have mainline kernel (~4.16.10, should I build grate kernel first?) and able to start X, so cool! %D

and trying to build mesa master brach:

```
sh autogen.sh
sh configure --prefix=/usr \
 --enable-dri \
 --enable-glx \
 --enable-shared-glapi \
 --enable-texture-float \
 --disable-nine \
 --enable-debug \
 --enable-dri3 \
 --enable-egl \
 --enable-gbm \
 --enable-gles1 \
 --enable-gles2 \
 --enable-glx-tls \
 --enable-valgrind=auto \
 --enable-llvm-shared-libs \
 --with-dri-drivers=swrast \
 --with-gallium-drivers=swrast,tegra \
 --with-vulkan-drivers= \
 --with-egl-platforms=x11,drm \ 
 --disable-nine \
 --disable-llvm \
 --disable-omx \
 --disable-va \
 --disable-vdpau \
 --disable-xa \
 --disable-xvmc \
 --disable-gallium-osmesa
```

with no luck during `sh autogen.sh` , getting:

```
...
checking for libdrm >= 2.4.75 libdrm_intel >= 2.4.75... no
configure: error: Package requirements (libdrm >= 2.4.75 libdrm_intel >= 2.4.75) were not met:

No package 'libdrm_intel' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables I915_CFLAGS
and I915_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Am I missing something obvious here? Saw [this discussion](https://bugs.freedesktop.org/show_bug.cgi?id=93278) but not sure how to interpret it. Looks like I cannot exclude some intel i915 drivers from building?

**Comment by kusma** [comment]
Yeah, you're going to need [libdrm from here](https://github.com/grate-driver/libdrm), compiled with `--enable-tegra-experimental-api`.

**Comment by kusma** [comment]
You need to pass those arguments to autogen.sh, as autogen.sh automatically runs configure at the end with its arguments.

**Comment by a-andreyev** [comment]
Thank you! Sorry for my ignorance, missed `NOCONFIGURE=1` logic.
Changing this and flags `--with-gallium-drivers=swrast,grate` and `--disable-omx-bellagio` helped too,
building is starting, but right now I stuck at `libunwind`:
```
...
Making all in gallium
make[3]: Entering directory '/home/alarm/mesa/src/mesa/src/gallium'
Making all in auxiliary
make[4]: Entering directory '/home/alarm/mesa/src/mesa/src/gallium/auxiliary'
  CC       util/u_debug_stack.lo
In file included from /usr/include/libunwind.h:9,
                 from util/u_debug_stack.h:35,
                 from util/u_debug_stack.c:37:
util/u_debug_stack.c: In function ‘debug_backtrace_capture’:
util/u_debug_stack.c:114:4: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘asm’
    unw_getcontext(&context);
    ^~~~~~~~~~~~~~
util/u_debug_stack.c:114:4: error: lvalue required as left operand of assignment
    unw_getcontext(&context);
    ^~~~~~~~~~~~~~
util/u_debug_stack.c:114:4: error: ‘unw_base’ undeclared (first use in this function); did you mean ‘unw_ctx’?
    unw_getcontext(&context);
    ^~~~~~~~~~~~~~
util/u_debug_stack.c:114:4: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [Makefile:2229: util/u_debug_stack.lo] Error 1
make[4]: Leaving directory '/home/alarm/mesa/src/mesa/src/gallium/auxiliary'
make[3]: *** [Makefile:621: all-recursive] Error 1
make[3]: Leaving directory '/home/alarm/mesa/src/mesa/src/gallium'
make[2]: *** [Makefile:869: all-recursive] Error 1
make[2]: Leaving directory '/home/alarm/mesa/src/mesa/src'
make[1]: *** [Makefile:660: all] Error 2
make[1]: Leaving directory '/home/alarm/mesa/src/mesa/src'
make: *** [Makefile:673: all-recursive] Error 1
```

Thank you for you help, it's not a problem for me to wait a couple of days if it's related to current branch state.

I'm researching current state of the tegra2 graphic stack support just for fun, pretty impressed this project exists and looks like no need to play with libhybris approach.

**Comment by kusma** [comment]
Yeah, that is a problem for all ARM-based builds AFAIK. You can disable libunwind to get around it...

**Comment by a-andreyev** [comment]
temporary `--disable-libunwind` helped.

Able to build mesa, thank you! Will follow the project to update build pkgbuild scripts and share them.

P.S.: pure magic :) default plasma desktop is not that should I ask for my device specs though :) 
![ac100](https://i.imgur.com/za02QbT.jpg)

**Comment by digetx** [comment]
Plasma is working nearly perfect on T20. Maybe it will get even better once we'll get some more GPU accell.

**Comment by a-andreyev** [comment]
provided [PKGBUILDs](https://aur.archlinux.org/packages/?K=aa13q&SeB=m), anyone feel free to fix/contribute :)

**Comment by digetx** [comment]
Awesome! Thank you very much! I think it's now worth to create a page with some basic building tips and useful links, I'll take a look into it now.

**Comment by digetx** [comment]
I've created a [wiki page](https://github.com/grate-driver/grate/wiki/Grate-driver) with the links and linked it in the grate-driver's organization description.
